# nixpacks.toml

[phases.setup]
cmds = [
    "echo '=== DETAILED DEBUGGING SETUP PHASE ==='",
    "echo 'Current directory:'",
    "pwd",
    "echo 'User info:'",
    "whoami",
    "echo 'Disk space:'",
    "df -h",
    "echo '--- Source directory listing ---'",
    "ls -la",
    "echo '--- Checking assets directory ---'",
    "ls -la assets/ || echo 'assets directory not found or not accessible'",
    "echo '--- Target directory preparation ---'",
    "mkdir -p /app/assets",
    "ls -ld /app/assets || echo 'Failed to create /app/assets'",
    "echo '--- Attempting file copy with detailed output ---'",
    # 使用逐一複製的方式，更容易診斷問題
    "for file in assets/*; do echo \"Copying $file to /app/assets/\"; cp \"$file\" /app/assets/ && echo \"✅ Success: $file\" || echo \"❌ Failed: $file\"; done",
    "echo '--- Final verification ---'",
    "ls -la /app/assets/ || echo 'Final listing failed'",
    "echo 'Total files copied:'",
    "ls /app/assets/ | wc -l || echo 'Count failed'",
    "echo '=== SETUP PHASE COMPLETE ==='"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 