# nixpacks.toml

[phases.setup]
cmds = [
    "echo '=== SETUP PHASE: Copying all assets from the assets directory ==='",
    "mkdir -p /app/assets",
    "cp -r assets/* /app/assets/",
    "echo '--- Listing copied assets in /app/assets/ ---'",
    "ls -la /app/assets/ || echo '/app/assets listing failed'",
    "echo '=== SETUP PHASE COMPLETE ==='"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 