# nixpacks.toml

# 告訴 Nixpacks 在設定階段需要安裝 rsync 套件
[phases.setup.pkgs]
rsync = "latest"

[phases.setup]
cmds = [
    "echo '=== DEBUGGING SETUP PHASE (using rsync) ==='",
    "echo 'Current directory:'",
    "pwd",
    "echo 'Listing contents of current directory:'",
    "ls -la",
    "echo '---'",
    
    "echo 'Attempting to copy assets with rsync...'",
    "mkdir -p /app/assets",
    # 使用 rsync -av 進行複製，-a 保留屬性，-v 提供詳細輸出
    "rsync -av assets/ /app/assets/",
    "echo '--- Verifying copied assets in /app/assets/ ---'",
    "ls -la /app/assets/ || echo 'Listing /app/assets/ failed, rsync might have been incomplete.'",
    "echo '=== SETUP PHASE COMPLETE ==='"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 