# nixpacks.toml

[phases.setup]
cmds = [
    "echo '=== SETUP PHASE: Copying rich_menu_images ==='",
    "ls -la rich_menu_images/ || echo 'rich_menu_images directory not found in source'",
    "mkdir -p /app/rich_menu_images || echo 'Failed to create /app/rich_menu_images'",
    "cp -r rich_menu_images/* /app/rich_menu_images/ 2>/dev/null || echo 'Failed to copy images'",
    "ls -la /app/rich_menu_images/ || echo '/app/rich_menu_images listing failed'",
    "echo '=== SETUP PHASE COMPLETE ==='",
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 