# nixpacks.toml

[phases.setup]
cmds = [
    "echo '=== DEBUGGING SETUP PHASE ==='",
    "echo 'Current directory:'",
    "pwd",
    "echo 'Listing contents of current directory:'",
    "ls -la",
    "echo 'Checking if assets directory exists:'",
    "if [ -d 'assets' ]; then echo 'assets directory FOUND.'; else echo 'assets directory NOT FOUND.'; fi",
    "echo '---'",
    
    "echo 'Attempting to copy assets...'",
    "mkdir -p /app/assets",
    # 使用 `cp -a` 來確保所有檔案屬性都被保留，並複製資料夾內容
    "cp -a assets/. /app/assets/",
    "echo '--- Listing copied assets in /app/assets/ ---'",
    "ls -la /app/assets/ || echo 'Listing /app/assets/ failed, copy might have been incomplete.'",
    "echo '=== SETUP PHASE COMPLETE ==='"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 