"""Add is_active to LineBotUser

Revision ID: 004_add_is_active_to_linebotuser
Revises: 003_add_missing_tables
Create Date: 2025-07-11 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004_add_is_active_to_linebotuser'
down_revision = '003_add_missing_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_bot_users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_bot_users', 'is_active')
    # ### end Alembic commands ### 